### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by prasanna532** [kakaobrain/word2word#8]
from word2word import Word2word
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\site-packages\word2word-1.0.0-py3.5.egg\word2word\__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 530, in spec_from_file_location
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\site-packages\word2word-1.0.0-py3.5.egg\word2word\word2word.py", line 44
    f"custom bilingual lexicon is only partially provided. "
                                                           ^
SyntaxError: invalid syntax

**Comment by yjchoe** [comment]
Hi @prasanna532,

It looks like you're using word2word with Python 3.5, but the package requires Python 3.6 or higher. 
Please try installing it with Python 3.6+ and see if the problem still exists. 

Thanks for trying out our package!
